//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Memento.Aspire.Core.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SharedResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SharedResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Memento.Aspire.Core.Resources.SharedResources", typeof(SharedResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author.
        /// </summary>
        public static string AUTHOR {
            get {
                return ResourceManager.GetString("AUTHOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birth Date.
        /// </summary>
        public static string AUTHOR_BIRTHDATE {
            get {
                return ResourceManager.GetString("AUTHOR_BIRTHDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Books.
        /// </summary>
        public static string AUTHOR_BOOKS {
            get {
                return ResourceManager.GetString("AUTHOR_BOOKS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string AUTHOR_NAME {
            get {
                return ResourceManager.GetString("AUTHOR_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book.
        /// </summary>
        public static string BOOK {
            get {
                return ResourceManager.GetString("BOOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author.
        /// </summary>
        public static string BOOK_AUTHOR {
            get {
                return ResourceManager.GetString("BOOK_AUTHOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Genre.
        /// </summary>
        public static string BOOK_GENRE {
            get {
                return ResourceManager.GetString("BOOK_GENRE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string BOOK_NAME {
            get {
                return ResourceManager.GetString("BOOK_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Release Date.
        /// </summary>
        public static string BOOK_RELEASEDATE {
            get {
                return ResourceManager.GetString("BOOK_RELEASEDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The creation was successful..
        /// </summary>
        public static string CONTROLLER_CREATE_SUCCESSFUL {
            get {
                return ResourceManager.GetString("CONTROLLER_CREATE_SUCCESSFUL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The deletion was successful..
        /// </summary>
        public static string CONTROLLER_DELETE_SUCCESSFUL {
            get {
                return ResourceManager.GetString("CONTROLLER_DELETE_SUCCESSFUL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The query was successful..
        /// </summary>
        public static string CONTROLLER_GET_ALL_SUCCESSFUL {
            get {
                return ResourceManager.GetString("CONTROLLER_GET_ALL_SUCCESSFUL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The query was successful..
        /// </summary>
        public static string CONTROLLER_GET_SUCCESSFUL {
            get {
                return ResourceManager.GetString("CONTROLLER_GET_SUCCESSFUL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The update was successful..
        /// </summary>
        public static string CONTROLLER_UPDATE_SUCCESSFUL {
            get {
                return ResourceManager.GetString("CONTROLLER_UPDATE_SUCCESSFUL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created At.
        /// </summary>
        public static string ENTITY_CREATEDAT {
            get {
                return ResourceManager.GetString("ENTITY_CREATEDAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created By.
        /// </summary>
        public static string ENTITY_CREATEDBY {
            get {
                return ResourceManager.GetString("ENTITY_CREATEDBY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identifier.
        /// </summary>
        public static string ENTITY_ID {
            get {
                return ResourceManager.GetString("ENTITY_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated At.
        /// </summary>
        public static string ENTITY_UPDATEDAT {
            get {
                return ResourceManager.GetString("ENTITY_UPDATEDAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated By.
        /// </summary>
        public static string ENTITY_UPDATEDBY {
            get {
                return ResourceManager.GetString("ENTITY_UPDATEDBY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field &apos;{0}&apos; already exists..
        /// </summary>
        public static string ERROR_DUPLICATE_FIELD {
            get {
                return ResourceManager.GetString("ERROR_DUPLICATE_FIELD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The combination of the fields &apos;{0}&apos; already exists..
        /// </summary>
        public static string ERROR_DUPLICATE_FIELD_COMBINATION {
            get {
                return ResourceManager.GetString("ERROR_DUPLICATE_FIELD_COMBINATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field &apos;{0}&apos; is invalid..
        /// </summary>
        public static string ERROR_INVALID_FIELD {
            get {
                return ResourceManager.GetString("ERROR_INVALID_FIELD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} does not exist..
        /// </summary>
        public static string ERROR_NOT_FOUND {
            get {
                return ResourceManager.GetString("ERROR_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error unexpected error occurred. Please try again later..
        /// </summary>
        public static string ERROR_UNEXPECTED {
            get {
                return ResourceManager.GetString("ERROR_UNEXPECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The request is invalid..
        /// </summary>
        public static string ERROR_VALIDATION {
            get {
                return ResourceManager.GetString("ERROR_VALIDATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Genre.
        /// </summary>
        public static string GENRE {
            get {
                return ResourceManager.GetString("GENRE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Books.
        /// </summary>
        public static string GENRE_BOOKS {
            get {
                return ResourceManager.GetString("GENRE_BOOKS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string GENRE_NAME {
            get {
                return ResourceManager.GetString("GENRE_NAME", resourceCulture);
            }
        }
    }
}
